-- AlphaMind Database Initialization
SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS alphamind_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

REVOKE ALL PRIVILEGES ON *.* FROM IF EXISTS 'alphamind_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER ON alphamind_db.* TO 'alphamind_user'@'%';
FLUSH PRIVILEGES;
