---
apiVersion: v1
kind: Service
metadata:
  name: alphamind-backend
  labels:
    app: alphamind-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000 # matches FastAPI containerPort
      protocol: TCP
      name: http
  selector:
    app: alphamind-backend
